cache:
  paths:
  - vendor/

stages:
  - build
  - test
  - deploy

test_job:
  stage: test
  script:
   - echo 'test'

#"PHP Mess Detector":
#  stage: test
#  script:
#    - curl -sS https://getcomposer.org/installer | php > /dev/null
#    - php composer.phar install --no-plugins
#    - wget -c http://static.phpmd.org/php/latest/phpmd.phar --no-check-certificate
#    - php phpmd.phar ./ text ./rulesets/cleancode.xml,./rulesets/controversial.xml,./rulesets/naming.xml,design --suffixes php --exclude vendor,cache,compiled,public,_ide_helper
