<?php

namespace App\Providers;

use Illuminate\Foundation\Support\Providers\EventServiceProvider as ServiceProvider;
use Illuminate\Support\Facades\Event;

class EventServiceProvider extends ServiceProvider
{
    /**
     * The event listener mappings for the application.
     *
     * @var array
     */
    protected $listen = [

    ];

    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        Event::listen('event.*', function ($eventName, array $data) {
            logger('test');
        });
    }
}
